const Alphabet = new Map([
    ["g/k", {
        "hangulLetterElement": '<div class="letter" id="g/k" character="ㄱ" answer="g/k" type="Consonant">ㄱ</div',
        "romanjiInitialLetter": '<div class="letter" id="g" character="ㄱ" answer="g/k">g</div',
        "romanjiFinalLetter": '<div class="letter" id="k" character="ㄱ" answer="k">g</div',
        "romanjiBothLetter": '<div class="letter" id="g/k" character="ㄱ" answer="g/k">g/k</div',
        "classification": "Consonants",
        "character": "ㄱ",
        "romanji": "g/k",
    }],
    ["n", {
        "hangulLetterElement": '<div class="letter" id="n">ㄴ</div',
        "romanjiBeginningLetter": '<div class="letter" id="n">n</div',
        "romanjiEndingLetter": '<div class="letter" id="n">n</div',
        "romanjiBothLetter": '<div class="letter" id="n">n</div',
        "classification": "Consonants",
        "character": "ㄴ",
        "romanji": "n",
    }],
    ["d/t", {
        "hangulLetterElement": '<div class="letter" id="d/t">ㄷ</div',
        "romanjiBeginningLetter": '<div class="letter" id="d">d</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="d/t">d/t</div',
        "classification": "Consonants",
        "character": "ㄷ",
        "romanji": "d/t",
    }],
    ["r/l", {
        "hangulLetterElement": '<div class="letter" id="r/l">ㄹ</div',
        "romanjiBeginningLetter": '<div class="letter" id="r">r</div',
        "romanjiEndingLetter": '<div class="letter" id="l">l</div',
        "romanjiBothLetter": '<div class="letter" id="r/l">r/l</div',
        "classification": "Consonants",
        "character": "ㄹ",
        "romanji": "r/l",
    }],
    ["m", {
        "hangulLetterElement": '<div class="letter" id="m">ㅁ</div',
        "romanjiBeginningLetter": '<div class="letter" id="m">m</div',
        "romanjiEndingLetter": '<div class="letter" id="m">m</div',
        "romanjiBothLetter": '<div class="letter" id="m">m</div',
        "classification": "Consonants",
        "character": "ㅁ",
        "romanji": "m",
    }],
    ["b/p", {
        "hangulLetterElement": '<div class="letter" id="b/p">ㅂ</div',
        "romanjiBeginningLetter": '<div class="letter" id="b">b</div',
        "romanjiEndingLetter": '<div class="letter" id="p">p</div',
        "romanjiBothLetter": '<div class="letter" id="b/p">b/p</div',
        "classification": "Consonants",
        "character": "ㅂ",
        "romanji": "b/p",
    }],
    ["s/t", {
        "hangulLetterElement": '<div class="letter" id="s/t">ㅅ</div',
        "romanjiBeginningLetter": '<div class="letter" id="s">s</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="s/t">s/t</div',
        "classification": "Consonants",
        "character": "ㅅ",
        "romanji": "s/t",
    }],
    ["ng", {
        "hangulLetterElement": '<div class="letter" id="ng">ㅇ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ng">ng</div',
        "romanjiEndingLetter": '<div class="letter" id="ng">ng</div',
        "romanjiBothLetter": '<div class="letter" id="ng">ng</div',
        "classification": "Consonants",
        "character": "ㅇ",
        "romanji": "ng",
    }],
    ["j/t", {
        "hangulLetterElement": '<div class="letter" id="j/t">ㅈ</div',
        "romanjiBeginningLetter": '<div class="letter" id="j">j</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="j/t">j/t</div',
        "classification": "Consonants",
        "character": "ㅈ",
        "romanji": "j/t",
    }],
    ["h/t", {
        "hangulLetterElement": '<div class="letter" id="h/t">ㅎ</div',
        "romanjiBeginningLetter": '<div class="letter" id="h">h</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="h/t">h/t</div',
        "classification": "Consonants",
        "character": "ㅎ",
        "romanji": "h/t",
    }],
    ["p", {
        "hangulLetterElement": '<div class="letter" id="p">ㅍ</div',
        "romanjiBeginningLetter": '<div class="letter" id="p">p</div',
        "romanjiEndingLetter": '<div class="letter" id="p">p</div',
        "romanjiBothLetter": '<div class="letter" id="p">p</div',
        "classification": "Consonants",
        "character": "ㅍ",
        "romanji": "p",
    }],
    ["ch/t", {
        "hangulLetterElement": '<div class="letter" id="ch/t">ㅊ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ch">ch</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="ch/t">ch/t</div',
        "classification": "Aspirated Consonants",
        "character": "ㅊ",
        "romanji": "ch/t",
    }],
    ["k", {
        "hangulLetterElement": '<div class="letter" id="k">ㅋ</div',
        "romanjiBeginningLetter": '<div class="letter" id="k">k</div',
        "romanjiEndingLetter": '<div class="letter" id="k">k</div',
        "romanjiBothLetter": '<div class="letter" id="k">k</div',
        "classification": "Aspirated Consonants",
        "character": "ㅋ",
        "romanji": "k",
    }],
    ["t", {
        "hangulLetterElement": '<div class="letter" id="t">ㅌ</div',
        "romanjiBeginningLetter": '<div class="letter" id="t">t</div',
        "romanjiEndingLetter": '<div class="letter" id="t">t</div',
        "romanjiBothLetter": '<div class="letter" id="t">t</div',
        "classification": "Aspirated Consonants",
        "character": "ㅌ",
        "romanji": "t",
    }],
    ["p", {
        "hangulLetterElement": '<div class="letter" id="p">ㅍ</div',
        "romanjiBeginningLetter": '<div class="letter" id="p">p</div',
        "romanjiEndingLetter": '<div class="letter" id="p">p</div',
        "romanjiBothLetter": '<div class="letter" id="p">p</div',
        "classification": "Aspirated Consonants",
        "character": "ㅍ",
        "romanji": "p",
    }],
    ["a", {
        "hangulLetterElement": '<div class="letter" id="a">ㅏ</div',
        "romanjiBeginningLetter": '<div class="letter" id="a">a</div',
        "romanjiEndingLetter": '<div class="letter" id="a">a</div',
        "romanjiBothLetter": '<div class="letter" id="a">a</div',
        "classification": "Vowels",
        "character": "ㅏ",
        "romanji": "a",
    }],
    ["ae", {
        "hangulLetterElement": '<div class="letter" id="ae">ㅐ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ae">ae</div',
        "romanjiEndingLetter": '<div class="letter" id="ae">ae</div',
        "romanjiBothLetter": '<div class="letter" id="ae">ae</div',
        "classification": "Vowels",
        "character": "ㅐ",
        "romanji": "ae",
    }],
    ["eo", {
        "hangulLetterElement": '<div class="letter" id="eo">ㅓ</div',
        "romanjiBeginningLetter": '<div class="letter" id="eo">eo</div',
        "romanjiEndingLetter": '<div class="letter" id="eo">eo</div',
        "romanjiBothLetter": '<div class="letter" id="eo">eo</div',
        "classification": "Vowels",
        "character": "ㅓ",
        "romanji": "eo",
    }],
    ["e", {
        "hangulLetterElement": '<div class="letter" id="e">ㅔ</div',
        "romanjiBeginningLetter": '<div class="letter" id="e">e</div',
        "romanjiEndingLetter": '<div class="letter" id="e">e</div',
        "romanjiBothLetter": '<div class="letter" id="e">e</div',
        "classification": "Vowels",
        "character": "ㅔ",
        "romanji": "e",
    }],
    ["eu", {
        "hangulLetterElement": '<div class="letter" id="eu">ㅡ</div',
        "romanjiBeginningLetter": '<div class="letter" id="eu">eu</div',
        "romanjiEndingLetter": '<div class="letter" id="eu">eu</div',
        "romanjiBothLetter": '<div class="letter" id="eu">eu</div',
        "classification": "Vowels",
        "character": "ㅡ",
        "romanji": "eu",
    }],
    ["i", {
        "hangulLetterElement": '<div class="letter" id="i">ㅣ</div',
        "romanjiBeginningLetter": '<div class="letter" id="i">i</div',
        "romanjiEndingLetter": '<div class="letter" id="i">i</div',
        "romanjiBothLetter": '<div class="letter" id="i">i</div',
        "classification": "Vowels",
        "character": "ㅣ",
        "romanji": "i",
    }],
    ["ya", {
        "hangulLetterElement": '<div class="letter" id="ya">ㅑ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ya">ya</div',
        "romanjiEndingLetter": '<div class="letter" id="ya">ya</div',
        "romanjiBothLetter": '<div class="letter" id="ya">ya</div',
        "classification": "Y Vowels",
        "character": "ㅑ",
        "romanji": "ya",
    }],
    ["yae", {
        "hangulLetterElement": '<div class="letter" id="yae">ㅒ</div',
        "romanjiBeginningLetter": '<div class="letter" id="yae">yae</div',
        "romanjiEndingLetter": '<div class="letter" id="yae">yae</div',
        "romanjiBothLetter": '<div class="letter" id="yae">yae</div',
        "classification": "Y Vowels",
        "character": "ㅒ",
        "romanji": "yae",
    }],
    ["yeo", {
        "hangulLetterElement": '<div class="letter" id="yeo">ㅕ</div',
        "romanjiBeginningLetter": '<div class="letter" id="yeo">yeo</div',
        "romanjiEndingLetter": '<div class="letter" id="yeo">yeo</div',
        "romanjiBothLetter": '<div class="letter" id="yeo">yeo</div',
        "classification": "Y Vowels",
        "character": "ㅕ",
        "romanji": "yeo",
    }],
    ["ye", {
        "hangulLetterElement": '<div class="letter" id="ye">ㅖ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ye">ye</div',
        "romanjiEndingLetter": '<div class="letter" id="ye">ye</div',
        "romanjiBothLetter": '<div class="letter" id="ye">ye</div',
        "classification": "Y Vowels",
        "character": "ㅖ",
        "romanji": "ye",
    }],
    ["yo", {
        "hangulLetterElement": '<div class="letter" id="yo">ㅛ</div',
        "romanjiBeginningLetter": '<div class="letter" id="yo">yo</div',
        "romanjiEndingLetter": '<div class="letter" id="yo">yo</div',
        "romanjiBothLetter": '<div class="letter" id="yo">yo</div',
        "classification": "Y Vowels",
        "character": "ㅛ",
        "romanji": "yo",
    }],
    ["yu", {
        "hangulLetterElement": '<div class="letter" id="yu">ㅠ</div',
        "romanjiBeginningLetter": '<div class="letter" id="yu">yu</div',
        "romanjiEndingLetter": '<div class="letter" id="yu">yu</div',
        "romanjiBothLetter": '<div class="letter" id="yu">yu</div',
        "classification": "Y Vowels",
        "character": "ㅠ",
        "romanji": "yu",
    }],
    ["wa", {
        "hangulLetterElement": '<div class="letter" id="wa">ㅘ</div',
        "romanjiBeginningLetter": '<div class="letter" id="wa">wa</div',
        "romanjiEndingLetter": '<div class="letter" id="wa">wa</div',
        "romanjiBothLetter": '<div class="letter" id="wa">wa</div',
        "classification": "Diphthongs",
        "character": "ㅘ",
        "romanji": "wa",
    }],
    ["wae", {
        "hangulLetterElement": '<div class="letter" id="wae">ㅙ</div',
        "romanjiBeginningLetter": '<div class="letter" id="wae">wae</div',
        "romanjiEndingLetter": '<div class="letter" id="wae">wae</div',
        "romanjiBothLetter": '<div class="letter" id="wae">wae</div',
        "classification": "Diphthongs",
        "character": "ㅙ",
        "romanji": "wae",
    }],
    ["oe", {
        "hangulLetterElement": '<div class="letter" id="oe">ㅚ</div',
        "romanjiBeginningLetter": '<div class="letter" id="oe">oe</div',
        "romanjiEndingLetter": '<div class="letter" id="oe">oe</div',
        "romanjiBothLetter": '<div class="letter" id="oe">oe</div',
        "classification": "Diphthongs",
        "character": "ㅚ",
        "romanji": "oe",
    }],
    ["wo", {
        "hangulLetterElement": '<div class="letter" id="wo">ㅝ</div',
        "romanjiBeginningLetter": '<div class="letter" id="wo">wo</div',
        "romanjiEndingLetter": '<div class="letter" id="wo">wo</div',
        "romanjiBothLetter": '<div class="letter" id="wo">wo</div',
        "classification": "Diphthongs",
        "character": "ㅝ",
        "romanji": "wo",
    }],
    ["we", {
        "hangulLetterElement": '<div class="letter" id="we">ㅞ</div',
        "romanjiBeginningLetter": '<div class="letter" id="we">we</div',
        "romanjiEndingLetter": '<div class="letter" id="we">we</div',
        "romanjiBothLetter": '<div class="letter" id="we">we</div',
        "classification": "Diphthongs",
        "character": "ㅞ",
        "romanji": "we",
    }],
    ["wi", {
        "hangulLetterElement": '<div class="letter" id="wi">ㅟ</div',
        "romanjiBeginningLetter": '<div class="letter" id="wi"wi</div',
        "romanjiEndingLetter": '<div class="letter" id="wi"wi</div',
        "romanjiBothLetter": '<div class="letter" id="wi"wi</div',
        "classification": "Diphthongs",
        "character": "ㅟ",
        "romanji": "wi",
    }],
    ["ui", {
        "hangulLetterElement": '<div class="letter" id="ui">ㅢ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ui">ui</div',
        "romanjiEndingLetter": '<div class="letter" id="ui">ui</div',
        "romanjiBothLetter": '<div class="letter" id="ui">ui</div',
        "classification": "Diphthongs",
        "character": "ㅢ",
        "romanji": "ui",
    }],
    ["kk", {
        "hangulLetterElement": '<div class="letter" id="kk">ㄲ</div',
        "romanjiBeginningLetter": '<div class="letter" id="kk">kk</div',
        "romanjiEndingLetter": '<div class="letter" id="kk">kk</div',
        "romanjiBothLetter": '<div class="letter" id="kk">kk</div',
        "classification": "Diphthongs",
        "character": "ㄲ",
        "romanji": "kk/k",
    }],
    ["tt", {
        "hangulLetterElement": '<div class="letter" id="tt">ㄸ</div',
        "romanjiBeginningLetter": '<div class="letter" id="tt">tt</div',
        "romanjiEndingLetter": '<div class="letter" id="tt">tt</div',
        "romanjiBothLetter": '<div class="letter" id="tt">tt</div',
        "classification": "Diphthongs",
        "character": "ㄸ",
        "romanji": "tt",
    }],
    ["pp", {
        "hangulLetterElement": '<div class="letter" id="pp">ㅃ</div',
        "romanjiBeginningLetter": '<div class="letter" id="pp">pp</div',
        "romanjiEndingLetter": '<div class="letter" id="pp">pp</div',
        "romanjiBothLetter": '<div class="letter" id="pp">pp</div',
        "classification": "Diphthongs",
        "character": "ㅃ",
        "romanji": "pp",
    }],
    ["ss", {
        "hangulLetterElement": '<div class="letter" id="ss">ㅆ</div',
        "romanjiBeginningLetter": '<div class="letter" id="ss">ss</div',
        "romanjiEndingLetter": '<div class="letter" id="ss">ss</div',
        "romanjiBothLetter": '<div class="letter" id="ss">ss</div',
        "classification": "Diphthongs",
        "character": "ㅆ",
        "romanji": "ss/t",
    }],
    ["jj", {
        "hangulLetterElement": '<div class="letter" id="jj">ㅉ</div',
        "romanjiBeginningLetter": '<div class="letter" id="jj">jj</div',
        "romanjiEndingLetter": '<div class="letter" id="jj">jj</div',
        "romanjiBothLetter": '<div class="letter" id="jj">jj</div',
        "classification": "Diphthongs",
        "character": "ㅉ",
        "romanji": "jj",
    }],
    ["o", {
        "hangulLetterElement": '<div class="letter" id="o">ㅗ</div',
        "romanjiBeginningLetter": '<div class="letter" id="o">o</div',
        "romanjiEndingLetter": '<div class="letter" id="o">o</div',
        "romanjiBothLetter": '<div class="letter" id="o">o</div',
        "classification": "Vowels",
        "character": "ㅗ",
        "romanji": "o",
    }],
    ["u", {
        "hangulLetterElement": '<div class="letter" id="u">ㅜ</div',
        "romanjiBeginningLetter": '<div class="letter" id="u">u</div',
        "romanjiEndingLetter": '<div class="letter" id="u">u</div',
        "romanjiBothLetter": '<div class="letter" id="u">u</div',
        "classification": "Vowels",
        "character": "ㅜ",
        "romanji": "u",
    }],
]);